### ISSUE TITLE
Handle case where input granules are empty

### ISSUE THREAD

**Issue by skorper** [podaac/concise#10]
There are cases where one of the the concise input granules is empty. One example is an L2SS-Py + Concise chain with ASCAT L2 data. The swath has a spatial extent of -180,-90,180,90 (global) but a subset of this data may return an empty granule. When this happens Concise encounters errors. Instead, Concise should elegantly handle this scenario, probably by discarding the empty granule in the result.

**Comment by skorper** [comment]
This is causing the following error:

> Unexpected token p in JSON at position 1

The stack trace is:

> Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/worker/podaac/merger/preprocess_worker.py", line 292, in _run_worker
    process_groups(dataset, group_list, max_dims, group_metadata, var_metadata, var_info)
  File "/worker/podaac/merger/preprocess_worker.py", line 336, in process_groups
    get_variable_data(parent_group, var_info, var_metadata)
  File "/worker/podaac/merger/preprocess_worker.py", line 428, in get_variable_data
    raise RuntimeError('Inconsistent variable schemas')
RuntimeError: Inconsistent variable schemas

and can be recreated with the following request: 

https://harmony.earthdata.nasa.gov/C2075141559-POCLOUD/ogc-api-coverages/1.0.0/collections/wind_speed,wind_dir/coverage/rangeset?forceAsync=true&subset=lat(-90%3A0)&subset=lon(-180%3A0)&subset=time(%222021-12-20T00%3A00%3A00%22%3A%222021-12-20T23%3A59%3A59.999999%22)&concatenate=true

**Comment by sliu008** [comment]
https://github.com/podaac/concise/pull/15/files

**Comment by frankinspace** [comment]
Seems as though this is still an issue.

I tried running 

https://harmony.earthdata.nasa.gov/C2075141559-POCLOUD/ogc-api-coverages/1.0.0/collections/wind_speed,wind_dir/coverage/rangeset?forceAsync=true&subset=lat(-90%3A0)&subset=lon(-180%3A0)&subset=time(%222021-12-20T00%3A00%3A00%22%3A%222021-12-20T23%3A59%3A59.999999%22)&concatenate=true

again in prod and got 

```
"WorkItem [111007] failed with error: ghcr.io/podaac/concise:0.3.0: Service request failed with an unknown error"
```

Looking into the kibana logs turned up:

```
File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/worker/podaac/merger/preprocess_worker.py", line 299, in _run_worker
    process_groups(dataset, group_list, max_dims, group_metadata, var_metadata, var_info)
  File "/worker/podaac/merger/preprocess_worker.py", line 343, in process_groups
    get_variable_data(parent_group, var_info, var_metadata)
  File "/worker/podaac/merger/preprocess_worker.py", line 436, in get_variable_data
    raise RuntimeError('Inconsistent variable schemas')
RuntimeError: Inconsistent variable schemas
```

According to https://harmony.earthdata.nasa.gov/versions, l2ss-py version is 1.4.0 and concise is 0.3.0.

**Comment by skorper** [comment]
I'm wondering if there could be something else going on here. I tested this with the following request

```
https://harmony.earthdata.nasa.gov/C2075141559-POCLOUD/ogc-api-coverages/1.0.0/collections/wind_speed,wind_dir/coverage/rangeset?forceAsync=true&subset=lat(-30%3A30)&subset=lon(-60%3A60)&concatenate=true&maxResults=15
```

This succeeds, and looking at each layer in Panoply it seems like at least 2 of the input granules were empty.

**Comment by sliu008** [comment]
I looked into this if we ran this https://harmony.earthdata.nasa.gov/C2075141559-POCLOUD/ogc-api-coverages/1.0.0/collections/wind_speed,wind_dir/coverage/rangeset?forceAsync=true&subset=lat(-90%3A0)&subset=lon(-180%3A0)&subset=time(%222021-12-20T00%3A00%3A00%22%3A%222021-12-20T23%3A59%3A59.999999%22) which results in just subsetted files, I noticed that one of the files was not subsetted or didn't have the subsetted filename, i tried concise with these files and it was the one without the subsetted filename that cause the problem.

**Comment by sliu008** [comment]
After further looking into the files it seem like the difference was found in the time variable.
The file without subset in the file
name:time dim_order:('NUMROWS', 'NUMCELLS') fill_value:1.0000000150474662e+30 datatype:float64 group_path:/

The subsetted files
name:time dim_order:('NUMROWS', 'NUMCELLS') fill_value:1.0000000150474662e+30 datatype:float32 group_path:/

**Comment by skorper** [comment]
Based on Simon's investigation, I think we can close this issue. The above issue will be tracked here: https://github.com/podaac/l2ss-py/issues/80
