### ISSUE TITLE
Error when trying to run l2ss-concise chain in Harmony

### ISSUE THREAD

**Issue by indiejames** [podaac/concise#4]
I'm attempting to test the new l2ss-concise chain in Harmony and I encountered an error:

```
2021-11-17T16:52:52.435Z [debug]: FROM WORKER LOG: ERROR:root:Variable schemas are inconsistent between granules
```

Not sure how to upload the data files involved here.

**Comment by frankinspace** [comment]
These were the outputs of the subset operation that were sent as input to concise:
[Archive.zip](https://github.com/podaac/concise/files/7557206/Archive.zip)

**Comment by frankinspace** [comment]
I did an `ncdump -ch` on both files and compared the output. The only difference between the two is the size of the time dimension (which I don't think concise is checking) and some global attributes; so not totally sure why we're hitting this error.

**Comment by skorper** [comment]
The issue is that `np.nan != np.nan` on [this line](https://github.com/podaac/concise/blob/develop/podaac/merger/variable_info.py#L49). I will open a PR to fix this issue.

**Comment by indiejames** [comment]
Just tested with ghcr.io/podaac/concise:sit and seems to be working now.
