### ISSUE TITLE
Add version of concise (like we do with l2ss-py) to history_json in merged granule files through harmony

### ISSUE THREAD

**Issue by jamesfwood** [podaac/concise#76]
Reported by @davidcolemanjpl to help him get the version deployed in UAT/OPS.

**Comment by sliu008** [comment]
we already have history in concise in the resulting file

https://github.com/podaac/concise/blob/develop/podaac/merger/preprocess_worker.py#L79

**Comment by jamesfwood** [comment]
Already done.

**Comment by davidcolemanjpl** [comment]
Is there a way to update the CONCISE version to display in the Harmony UI (UAT) UI? 
Currently in Harmony UI, the version for CONCISE is noted as :
"podaac/concise:uat"

note: In Harmony UI (OPS),  the CONCISE version is noted as :
"podaac/concise:0.6.1"
