### ISSUE TITLE
Update UMM-S record to specify support for concatenation

### ISSUE THREAD

**Issue by frankinspace** [podaac/concise#86]
The CMR now supports ingesting UMM-S records that specify concatenation in all of its environments. That means we can start updating our UMM-S records (see https://bugs.earthdata.nasa.gov/browse/ECSE-1372) and EDSC will soon make use of this information to allow users to request concatenation.

**Comment by frankinspace** [comment]
Edit should be made to concise/cmr/[concise_cmr_umm_s.json](https://github.com/podaac/concise/tree/develop/cmr/concise_cmr_umm_s.json)

**Comment by jamesfwood** [comment]
Here's an example:
https://cmr.uat.earthdata.nasa.gov/search/services.umm_json?concept_id=S1239265626-EEDTEST

**Comment by jamesfwood** [comment]
All done except waiting for this PR to be merged:
https://github.com/nasa/harmony/pull/501

**Comment by jamesfwood** [comment]
@davidcolemanjpl please verify that the **Concise** service and **Concise Chain** service in UAT and OPS contain the new service option for aggregation concatenation.

Should be showing something like this in CMR:

"ServiceOptions": {
        "Aggregation": {
            "Concatenate": {
                "ConcatenateDefault": true
            }
        }
    },

Verify both services meets all requirements for this ticket:
https://bugs.earthdata.nasa.gov/browse/ECSE-1372

Thanks!

**Comment by jamesfwood** [comment]
@davidcolemanjpl don't worry about testing this one either.  Thanks!
