### ISSUE TITLE
Concise: Make a new release for TEMPO update

### ISSUE THREAD

**Issue by jamesfwood** [podaac/concise#98]
Release after this is merged:

- https://github.com/podaac/concise/issues/96

**Comment by jamesfwood** [comment]
@davidcolemanjpl Please test concise in HITIDE UAT.  It should be version 0.8.0rc1

Test procedure/details, refer to this:
https://github.com/podaac/concise/pull/101

**Comment by davidcolemanjpl** [comment]
**CONCISE v0.8.0rc1**
HiTIDE UI (UAT) v4.17.0-RC.6
l2ss-py:v2.8.0rc3


**_Test Complete_** 


Cloud-Collections under test:
**JASON-1_L2_OST_GPN_E**:
Harmony JobID(s): bffbad6a-e6f2-413c-8409-903da2e2a58b or 162230a7-e564-4e35-bcda-a8b207b571c3
Job Status:  https://harmony.uat.earthdata.nasa.gov/jobs/bffbad6a-e6f2-413c-8409-903da2e2a58b


**AMSR2-REMSS-L2P-v8.2**:
Harmony JobID: 5a43e066-3854-436c-bc6e-53f1a3e56444
Job Status: https://harmony.uat.earthdata.nasa.gov/jobs/5a43e066-3854-436c-bc6e-53f1a3e56444

**Comment by jamesfwood** [comment]
Done
